name: Docs
on:
  push:
    branches:
      - main
jobs:
  update_docs:
    name: Update Docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update Docs
        run: |
          mkdir -p ./ponyc
          wget -q https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz
          tar xzf ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz --directory ./ponyc --strip-components=1
          mkdir -p ./corral
          wget -q https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-unknown-linux.tar.gz
          tar xzf corral-x86-64-unknown-linux.tar.gz --directory ./corral --strip-components=1
          export PATH=`pwd`/ponyc/bin:`pwd`/corral/bin:$PATH
          corral fetch
          PONYC=./ponyc/bin/ponyc make test
          PONYC=./ponyc/bin/ponyc make docs
          cd build/eohippus-docs
          python -m mkdocs build
      - name: Checkout Docs Site
        uses: actions/checkout@v4
        with:
          repository: chalcolith/chalcolith.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: chalcolith.github.io
          fetch-depth: 0
      - name: Copy Files
        run: |
          pwd
          ls -al
