name: Ubuntu Build and Test
on:
  workflow_call:
jobs:
  ubuntu_build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Ubuntu Build and Test (${{ matrix.config }})
        run: |
          mkdir -p ./ponyc
          wget -q https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz
          tar xzf ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz --directory ./ponyc --strip-components=1
          mkdir -p ./corral
          wget -q https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-unknown-linux.tar.gz
          tar xzf corral-x86-64-unknown-linux.tar.gz --directory ./corral --strip-components=1
          export PATH=`pwd`/ponyc/bin:`pwd`/corral/bin:$PATH
          echo PonyC:
          ponyc --version
          echo Corral:
          corral version
          corral fetch
          PONYC=./ponyc/bin/ponyc make cli config=${{ matrix.config }}
          PONYC=./ponyc/bin/ponyc make fmt config=${{ matrix.config }}
          PONYC=./ponyc/bin/ponyc make lsp config=${{ matrix.config }}
          PONYC=./ponyc/bin/ponyc make test config=${{ matrix.config }}
