name: Ubuntu Build and Test
on:
  workflow_call:
jobs:
  ubuntu_build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Ubuntu Build and Test (${{ matrix.config }})
        run: |
          mkdir -p ponyc
          wget https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz
          tar xzf ponyc-x86-64-unknown-linux-ubuntu22.04.tar.gz --directory ponyc --strip-components=1
          mkdir -p corral
          wget https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-unknown-linux-ubuntu22.04.tar.gz
          tar xzf corral-x86-64-unknown-linux-ubuntu22.04.tar.gz --directory corral --strip-components=1
          export PATH=`pwd`/ponyc:`pwd`/corral:$PATH
          make fetch
          make cli config=${{ matrix.config }}
          make fmt config=${{ matrix.config }}
          make lsp config=${{ matrix.config }}
          make test config=${{ matrix.config }}
